trainFile = src/main/webapp/WEB-INF/ner-training/cv-train.tsv
serializeTo = src/main/webapp/WEB-INF/ner-training/cv-ner-model.ser.gz
map = word=0,answer=1

useClassFeature = true
useWord = true
useNGrams = true
maxNGramLeng = 6
usePrev = true
useNext = true
useSequences = true
usePrevSequences = true
maxLeft = 1
wordShape = chris2useLC
useTypeSeqs = true
useTypeSeqs2 = true
useTypeySequences = true
